name: crystalsystems

channels:
  - conda-forge

dependencies:
  - build
  - numpy
  - matplotlib
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - versioningit
  - pip:
    - check-wheel-contents
