name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,defaults
        mamba-version: "*"
        environment-file: environment.yml
        activate-environment: crystalsystems
    - name: Restore cached conda environment
      id: cache-load
      uses: actions/cache/restore@v3
      with:
        path: /usr/share/miniconda/envs/crystalsystems
        key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
    - name: Load Environment
      if: steps.cache-load.outputs.cache-hit != 'true'
      run: |
        mamba env update --file environment.yml  --prune
    - name: Run tests
      run: python -m pytest --cov=src --cov-report=xml --cov-report=term
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    - name: Build python wheel
      run: |
        python -m build --wheel --no-isolation
        check-wheel-contents dist/crystalsystems-*.whl
